プロダクトコード途中
JunyaMasuda/Msmash-API pull request #6
Opened 2022-08-29 15:10 UTC by fukayakoki

まだ途中だけどファイル構成とかドメインとか問題なさそうならこんな感じでどうだろうか？の指針

2022-08-30 14:59 UTC, JunyaMasuda commented
ちなみにPR作るときdraftってやつがあって、まだ作業中であることをアピールできるで
![スクリーンショット 2022-08-30 23 55 57](https://user-images.githubusercontent.com/49140566/187470688-0e33bfac-6f4a-4128-b4ca-6b7060d88329.png)

PR作成後でも右のここからdraftに変更できるよ〜
![スクリーンショット 2022-08-30 23 58 37](https://user-images.githubusercontent.com/49140566/187470997-bf1f1c3f-37d2-4239-b940-3ca535b342fe.png)

2022-08-30 15:12 UTC, yuki-miyamoto1998 commented
ひとまず手動で動作確認出来たらプッシュしてマージしちゃおー
（そしたらこちらもcontrollerやserviceファイルとかいじれる）

2022-08-31 16:15 UTC, fukayakoki commented
> ひとまず手動で動作確認出来たらプッシュしてマージしちゃおー
> （そしたらこちらもcontrollerやserviceファイルとかいじれる）

@yuki-miyamoto1998 
@JunyaMasuda 
user追加が手元で動かせたのでここまでの進捗をprで共有します。テストの中身はできてないけどフォルダとファイルだけ作ったから大きなコンフリクトはなく進めていけるはず。

@yuki-miyamoto1998 
昨日のmapperが読めないエラーだけど、
UserMapperがjava/hinatazaka46/smash/repository/mybatisにあったとしたら
UserMapper.xmlはresources/hinatazaka46/smash/repository/mybatisに配置しないとダメらしい。フォルダ構成を変更したらちゃんと動いた。
ここから先は憶測。
どうして個人開発演習で同じフォルダで動いていたかと言うと、application.ymlでmapper-locationでmapperの場所を指定していたからだと思う。(今回も個人開発演習と同じ方法でやろうとしてymlでパス指定して、ymlを読み込めるようにpomを設定したけど上手くいかなかった。ので上記の方法を採用した)

2022-09-02 14:49 UTC, JunyaMasuda commented
> @yuki-miyamoto1998 昨日のmapperが読めないエラーだけど、 UserMapperがjava/hinatazaka46/smash/repository/mybatisにあったとしたら UserMapper.xmlはresources/hinatazaka46/smash/repository/mybatisに配置しないとダメらしい。フォルダ構成を変更したらちゃんと動いた。 ここから先は憶測。 どうして個人開発演習で同じフォルダで動いていたかと言うと、application.ymlでmapper-locationでmapperの場所を指定していたからだと思う。(今回も個人開発演習と同じ方法でやろうとしてymlでパス指定して、ymlを読み込めるようにpomを設定したけど上手くいかなかった。他にも設定とか必要なのかな？？？ので上記の方法を採用した)

俺も気になってちょっと挑戦してみたけど確かにできんな...
projectに追加しておくわ

2022-09-05 13:47 UTC, yuki-miyamoto1998 requested changes
動作確認はローカルのmysqlに繋いだ感じかな？
そのあたりの具体的にどうやったかを軽くPRのどこかに書いてくれると助かるぜ。
例えば、「curl でローカルのMySQLにinsertできることを確認」みたいな感じかな。
実際に入力したcurlのコマンドも書いておいてくれると更にありがたい。
これ通りに書けばいけるのかな？？
https://qiita.com/Jazuma/items/5aa0a205f67c6dba9425

あとこれはお願いなんだけど、testフォルダにserviceフォルダも作ってくれると嬉しい<m(__)m>

2022-09-05 13:47 UTC, yuki-miyamoto1998 commented on pom.xml
> +            <artifactId>spring-boot-configuration-processor</artifactId>
細かいけどインデントずれてるのが気になる笑

2022-09-05 13:47 UTC, yuki-miyamoto1998 commented on pom.xml
> +            <artifactId>lombok</artifactId>
ここ二つもインデント

2022-09-05 13:47 UTC, yuki-miyamoto1998 commented on src/main/java/hinatazaka46/smash/Controller/HelloWorld.java
> +
これって動作確認用のファイルだっけ？
そうだったら動作確認手順を軽く書いてくれると助かる。
あとで単体テスト書いたら消してもいいかもね。

2022-09-05 13:47 UTC, yuki-miyamoto1998 commented on src/main/java/hinatazaka46/smash/Controller/UserContoroller.java
> +import lombok.NonNull;
使わないimport文は消しちゃった方が良いかも。他のファイルにもあるかも。
たしかショートカットキーで使わないimport全部消せたはず（やり方忘れた）

2022-09-05 13:47 UTC, yuki-miyamoto1998 commented on src/main/java/hinatazaka46/smash/Domain/User.java
> +    private String image;
ここのimageメンバに入る具体的な内容って決まってたっけ？（なんらかの画像に紐づく文字列？）
一応聞いたけど、とりあえずStringでいいと思う！

2022-09-05 13:47 UTC, yuki-miyamoto1998 commented on src/main/resources/application.yml
> +#    username: root
@JunyaMasuda 
今更だけど、これって実際のusernameとpass入ってる？笑笑
もしそうだったら今度変えておこう笑笑
（ファイルはこのままで大丈夫）

2022-09-05 15:00 UTC, JunyaMasuda commented on src/main/java/hinatazaka46/smash/Controller/HelloWorld.java
> +
一番最初の環境構築で適当に作ったやつだから消してよし

2022-09-05 15:03 UTC, JunyaMasuda commented on src/main/java/hinatazaka46/smash/Controller/UserContoroller.java
> +import lombok.NonNull;
いらないインポートを消したいファイルやディレクトリを右クリックすると 「Optimize import」って出るのだ
![スクリーンショット 2022-09-06 0 01 41](https://user-images.githubusercontent.com/49140566/188477499-662ae552-7761-409c-b705-391e9d5724e6.png)

2022-09-05 15:10 UTC, JunyaMasuda commented on src/main/java/hinatazaka46/smash/Domain/User.java
> +    private String image;
できたらいいなの想定の案で出てたからテーブルに追加してた
個人的には画像を直接MySQLに埋め込むのは流石にナンセンスだと思ったので、MySQLサーバとは違う別のストレージ(VPSのストレージでも、GoogleDriveとかでも)のpathを保存させておくのがいいのかなと思った
（正直どうするのがいいのか全くわかってない男の想像力だけでお話ししております...）
（良さげな方法知ってる人いない...?）

2022-09-05 15:12 UTC, JunyaMasuda commented on src/main/resources/application.yml
> +#    username: root
実際のものなのでまあよろしくないので強制的に編集させていただきました。
[Update application.yml](https://github.com/JunyaMasuda/Msmash-API/pull/6/commits/7f67857e91bd60a50606554f06226367367c6356)

（俺も気づかずに本物の情報を残したままdraftPRを出していたことは内緒）

2022-09-05 15:14 UTC, JunyaMasuda commented
ちなみに(マージしよ) ってレビューしてくれって意味？？

2022-09-05 15:29 UTC, fukayakoki commented
> ちなみに(マージしよ) ってレビューしてくれって意味？？

たくさんコメントついてるー
色々あるようなので少しずつ直して行ければと思います
『マージしよ』はブランチからブランチが切られてるのあんまよくない気がしたからレビューとか修正とかして早くdevelpにマージ出来たらいいな的な

2022-09-05 15:36 UTC, fukayakoki commented on src/main/java/hinatazaka46/smash/Domain/User.java
> +    private String image;
サーバ内に画像保存してpathをsqlに入れるので良いと思う

2022-09-07 12:21 UTC, JunyaMasuda commented on src/main/java/hinatazaka46/smash/Domain/User.java
> +    private String image;
なるほどな〜
確かにDBに全部あれば最悪全削除とか一部削除とかはpathが死んでないかとか確認する必要ないし、DBの中身だけ消せばいいもんなあ
単純に議論の余地はありそうだし次回みんなで集まった時とかで話題で出してみようか
(忘れないようにToDoリストに入れておく)

2022-09-20 14:26 UTC, fukayakoki commented
このprから派生したmjのユーザ検索がマージされたので、このprは閉じます。テストコードはまたissue作り直します

2022-09-20 14:27 UTC, closed without merging